// Add a confirmed brand and its local logo here. Keep relationship labels accurate.
// Artwork is stored locally so the strip does not rely on a third-party logo API.
export const BRANDS = [
  {
    name: 'BeastLife',
    logo: '/brands/beastlife.svg',
    width: 545,
    height: 249,
    relationship: 'In-house video editor',
    tone: 'dark',
  },
  {
    name: 'Anakage Technologies',
    logo: '/brands/anakage.png',
    width: 1920,
    height: 1200,
    relationship: 'Freelance editing',
    tone: 'dark',
    logoClass: 'brand-logo--anakage',
  },
  {
    name: 'Homversity',
    logo: '/brands/homversity-wordmark.svg',
    width: 133,
    height: 24,
    relationship: 'Freelance editing',
    tone: 'light',
  },
  {
    name: 'GrowMedia',
    wordmark: ['Grow', 'Media'],
    relationship: 'Performance video editor',
    tone: 'dark',
  },
  {
    name: 'Media Magnetix',
    logo: '/brands/media-magnetix.png',
    width: 1600,
    height: 237,
    relationship: 'Video editor',
    tone: 'light',
  },
  {
    name: 'Techstars Startup Weekend Dhamtari',
    logo: '/brands/techstars-startup-weekend.png',
    width: 400,
    height: 400,
    relationship: 'Dhamtari · Event video editing',
    tone: 'black',
    logoClass: 'brand-logo--techstars',
  },
  {
    name: 'micro1',
    logo: '/brands/micro1.svg',
    width: 89,
    height: 20,
    relationship: 'AI Trainer',
    tone: 'light',
    logoClass: 'brand-logo--micro1',
  },
  {
    name: 'Microsoft Learn Student Ambassadors · Rungta Chapter 1',
    logo: '/brands/mlsa.png',
    width: 1593,
    height: 1389,
    relationship: 'Rungta Chapter 1 · Lead Video Editor',
    tone: 'light',
    logoClass: 'brand-logo--mlsa',
  },
];
